export const SIDEBAR_FETCH = 'SIDEBAR_FETCH';

export const HOME_FETCH = 'HOME_FETCH';
export const HOME_FETCH_CANCEL = 'HOME_FETCH_CANCEL';
export const HOME_FETCH_FAILED = 'HOME_FETCH_FAILED';
export const HOME_FETCH_SUCCESS = 'HOME_FETCH_SUCCESS';

export const FOOTER_FETCH = 'FOOTER_FETCH';

export const SERVICES_FECTH = 'SERVICES_FECTH';
export const SERVICES_FECTH_CANCEL = 'SERVICES_FECTH_CANCEL';
export const SERVICES_FECTH_FAILED = 'SERVICES_FECTH_FAILED';
export const SERVICES_FECTH_SUCCESS = 'SERVICES_FECTH_SUCCESS';
